import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of service — ChessCoach AI",
  description: "The terms under which ChessCoach AI is provided.",
};

/**
 * Terms of service (NFR-PR2) — **required before launch**.
 *
 * ⚠️ Engineering draft, not legal advice, not lawyer-reviewed. The fair-play
 * section is the one that matters most to us operationally (NFR-L1) and is
 * stated plainly rather than buried.
 */
export default function TermsPage() {
  return (
    <main className="mx-auto flex max-w-2xl flex-col gap-6 px-4 py-10 text-sm">
      <header className="flex flex-col gap-2">
        <h1 className="text-2xl font-semibold tracking-tight">Terms of service</h1>
        <p className="text-black/60 dark:text-white/60">Last updated: 28 July 2026</p>
      </header>

      <div className="rounded-lg border border-amber-500/40 bg-amber-500/10 p-3">
        <p className="font-medium">Draft — pending legal review</p>
        <p className="mt-1 text-black/70 dark:text-white/70">
          Describes how the service currently works. Not yet reviewed by a lawyer.
        </p>
      </div>

      <section className="flex flex-col gap-2">
        <h2 className="text-lg font-semibold">Post-game analysis only</h2>
        <p>
          ChessCoach AI reviews games that are <strong>already finished</strong>. It does not, and
          will not, provide help during a game in progress.
        </p>
        <p>
          Using any tool for assistance during a live game breaks the fair-play rules of Lichess and
          Chess.com and can get your account banned. Do not attempt to use this service that way. We
          build it so that it cannot be used that way.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2 className="text-lg font-semibold">What the service is</h2>
        <p>
          A computer analysis of your finished games, explained in plain language. The written
          review is generated by an AI model from engine output. We check every move and square it
          mentions against your actual game before showing it to you, but the review is a study aid,
          not authoritative instruction.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2 className="text-lg font-semibold">Acceptable use</h2>
        <ul className="list-disc pl-5">
          <li>Analyze your own finished games, or public games you are entitled to view.</li>
          <li>Do not attempt to obtain assistance during live play.</li>
          <li>
            Do not use automated means to place load on the service or on the chess platforms we
            read from.
          </li>
        </ul>
      </section>

      <section className="flex flex-col gap-2">
        <h2 className="text-lg font-semibold">Availability</h2>
        <p>
          This is a preview. The service may be unavailable, and free usage is limited per day. If
          our AI provider is unavailable you will still receive the full engine analysis, without
          the written review.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2 className="text-lg font-semibold">Not affiliated</h2>
        <p>
          ChessCoach AI is independent and not affiliated with, endorsed by, or connected to Lichess
          or Chess.com. See our{" "}
          <a className="underline" href="/attribution">
            attribution page
          </a>{" "}
          for the open-source software we use.
        </p>
      </section>
    </main>
  );
}
